import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  instructions: [
    { type: 'autogenerated', dirName: '.' },
    {
      type: 'link',
      label: '📝 Feedback Form',
      href: 'https://forms.gle/Gk5vybAj7VpYno1eA',
    },
  ],
};

export default sidebars;
